source 'http://rubygems.org'

# gem 'rails', '3.0.0.beta4'

# Bundle edge Rails instead:
gem 'rails', :git => 'git://github.com/rails/rails.git', :tag => 'v3.0.0.beta4'

gem 'sqlite3-ruby', :require => 'sqlite3'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
gem "inherited_resources", :git => "git://github.com/josevalim/inherited_resources.git"
gem "devise", :git => "git://github.com/plataformatec/devise.git", :ref => '5f2a19d7844abf341ab355bfd7de21ae861c1aae'
gem "simple_form", :git => "git://github.com/plataformatec/simple_form.git", :ref => '35f9c01324fb2cb42dbede7f6482b9212f2eba5f'

# Bundle gems for certain environments:
# gem 'rspec', :group => :test
group :test do
  gem 'rspec-rails', '2.0.0.beta.11'
  gem 'webrat', '0.7.1'
end
